### ISSUE TITLE
intelmq-contactdb: postgres service is not started

### ISSUE THREAD

**Issue by wagner-intevation** [Intevation/intelmq-cb-mailgen-docker#12]
I noticed that the certbund contact expert can't connect to the contactdb:
```
Failed to connect to database!
Traceback (most recent call last):
  File "/opt/intelmq-certbund-contact/intelmq_certbund_contact/expert.py", line 45, in init
    self.connect_to_database()
  File "/opt/intelmq-certbund-contact/intelmq_certbund_contact/expert.py", line 56, in connect_to_database
    self.con = psycopg2.connect(database=self.parameters.database,
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
Is the server running on host "intelmq-contactdb" (172.19.0.8) and accepting
TCP/IP connections on port 5432?
```

Looking at the actual container it looks like posgres is not started or properly configured:
```
root@b6d36c1b1442:/opt# ss -tlpn
State       Recv-Q Send-Q                                                                         Local Address:Port                                                                                        Peer Address:Port              
LISTEN      0      4096                                                                              127.0.0.11:36625                                                                                                  *:*
root@b6d36c1b1442:/opt# /etc/init.d/postgresql status
root@b6d36c1b1442:/opt# /etc/init.d/postgresql start
[warn] No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).             
root@b6d36c1b1442:/opt# pstree -a
postgres
  ├─postgres
  ├─postgres
  ├─postgres
  ├─postgres
  ├─postgres
  ├─postgres
  └─postgres
```

**Comment by wagner-intevation** [comment]
Just hat the same error when trying to authenticate in fody. The issue resolved itself after some time. Strange effect.
